---
apiVersion: workload.nephio.org/v1alpha1
kind: NFConfig
metadata:
  name: smf-core-config
  namespace: oaicp
spec:
  configRefs:
    - apiVersion: cellular.nephio.org/v1alpha1
      kind: PLMN
      metadata:
        name: oai-plmn
      spec:
        plmnInfo:
          - plmnID:
              mcc: "001"
              mcc: "01"
            tac: 1
            nssai:
              - sst: 1
                sd: ffffff
                dnnInfo:
                  - name: internet
                    sessionType: ipv4
                    dns: 173.21.3.100
                    subnet: 10.1.0.0/24
---
apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata:
  name: smf-core
  namespace: oaicp
spec:
  provider: smf.openairinterface.org
  capacity:
    maxNFConnections: 5
    maxSessions: 500
  interfaces:
  - name: n4
    ipv4:
      address: 192.168.31.2/24
      gateway: 192.168.31.1
    vlanID: 31
  networkInstances:
  - name: vpc-internal
    interfaces:
    - n4
  parametersRefs:
  - name: smf-core-config
    apiVersion: workload.nephio.org/v1alpha1
    kind: NFConfig
