---
apiVersion: workload.nephio.org/v1alpha1
kind: NFConfig
metadata:
  name: upf-edge-config
  namespace: oai-upf
spec:
  configRefs:
    - apiVersion: cellular.nephio.org/v1alpha1
      kind: PLMN
      metadata:
        name: oai-plmn
      spec:
        plmnInfo:
          - plmnID:
              mcc: "208"
              mnc: "99"
            tac: 1
            nssai:
              - sst: 1
                sd: ffffff
                dnnInfo:
                  - name: internet
                    sessionType: ipv4
                    dns: 172.21.3.100
                    subnet: 10.1.0.0/24
---
apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata:
  name: upf-edge
  namespace: oai-upf
spec:
  provider: upf.openairinterface.org
  capacity:
    maxDownlinkThroughput: 5G
    maxUplinkThroughput: 5G
  parametersRefs:
  - name: upf-edge-config
    apiVersion: workload.nephio.org/v1alpha1
    kind: NFConfig
  interfaces:
  - name: n3
    ipv4:
      address: 192.168.30.3/24
      gateway: 192.168.30.1
    vlanID: 30
  - name: n4
    ipv4:
      address: 192.168.31.3/24
      gateway: 192.168.31.1
    vlanID: 31
  - name: n6
    ipv4:
      address: 172.21.10.2/22
      gateway: 172.21.11.254
    vlanID: 422
  networkInstances:
  - name: vpc-internal
    interfaces:
    - n4
  - name: vpc-internet
    interfaces:
    - n6
  - name: vpc-ran
    interfaces:
    - n3
    