apiVersion: ref.nephio.org/v1alpha1
kind: Config
metadata:
  name: upf-edge01-config
  namespace: oai-upf
spec:
  config:
    apiVersion: workload.nephio.org/v1alpha1
    kind: UPFDeployment
    metadata:
      name: upf-edge01-config
      namespace: oai-upf
    spec:
      logLevel: info
      image: 'selfix.sboai.cs.eurecom.fr/oai-upf:ci-tmp-pr-16-4deecd64'
      fqdn:
        nrf: 'nrf-regional.oaicp.svc.cluster.local'
        smf: 'smf-regional.oaicp.svc.cluster.local'
      nssai:
        - sst: 1
          sd: '0xFFFFFF'
---
apiVersion: workload.nephio.org/v1alpha1
kind: UPFDeployment
metadata:
  name: upf-edge01
  namespace: oai-upf
spec:
  capacity:
    maxDownlinkThroughput: 5G
    maxUplinkThroughput: 5G
  configRefs:
  - name: upf-edge01-config
    namespace: oai-upf
    apiVersion: ref.nephio.org/v1alpha1
    kind: Config
  interfaces:
  - name: n3
    ipv4:
      address: 172.3.0.254/24
      gateway: 172.3.0.1
    vlanID: 4
  - name: n4
    ipv4:
      address: 172.1.1.253/24
      gateway: 172.1.1.1
    vlanID: 2
  - name: n6
    ipv4:
      address: 172.0.1.254/24
      gateway: 172.0.1.1
    vlanID: 3
  networkInstances:
  - name: vpc-internal
    interfaces:
    - n4
  - name: vpc-internet
    dataNetworks:
    - name: internet
      pool:
      - prefix: 10.1.0.0/24
    interfaces:
    - n6
  - name: vpc-ran
    interfaces:
    - n3