apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
data:
  {{- range $key, $val := .Values.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}

# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: {{ .Chart.Name }}-configmap
# data:
#   nrue.conf: |
#       uicc0 = {
#       imsi = "{{ .Values.config.fullImsi }}";
#       key = "{{ .Values.config.fullKey }}";
#       opc= "{{ .Values.config.opc }}";
#       dnn= "{{ .Values.config.dnn }}";
#       nssai_sst="{{ .Values.config.nssaiSst }}";
#       nssai_sd="{{ .Values.config.nssaiSd }}";
#       }