################################################################################
# Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The OpenAirInterface Software Alliance licenses this file to You under
# the OAI Public License, Version 1.1  (the "License"); you may not use this file
# except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.openairinterface.org/?page_id=698
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the OpenAirInterface (OAI) Software Alliance:
#      contact@openairinterface.org
################################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: oaiops
  name: oai-ausf-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oai-ausf-operator-cluster-role
rules:
  - apiGroups: [""]
    resources: [events]
    verbs: [create]
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [get, list, watch, create, update, patch]
  # - apiGroups: ["workload.nephio.org"]
  #   resources: [ausfdeployments]
  #   verbs: [list, watch]
  - apiGroups: ["workload.nephio.org"]
    resources: [ausfdeployments,ausfdeployments/status]
    verbs: [list, watch, update, patch]
  - apiGroups: [""]
    resources: [pods, serviceaccounts, configmaps, services, persistentvolumeclaims]
    verbs:  [get, list, watch, create, update, patch, delete]
  - apiGroups: ["apps","extensions"]
    resources: [deployments,deployments/status]
    verbs:  [get, list, watch, create, update, patch, delete]
  - apiGroups: ["k8s.cni.cncf.io"]
    resources: [network-attachment-definitions]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]
  - apiGroups: [admissionregistration.k8s.io/v1, admissionregistration.k8s.io/v1beta1]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oai-ausf-operator-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oai-ausf-operator-cluster-role
subjects:
  - kind: ServiceAccount
    name: oai-ausf-operator
    namespace: oaiops
## In case you want to restrict to a namespace uncomment this role and remove the rights from cluster role
#---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   namespace: oaiops
#   name: oai-ausf-operator-role
# rules:
#   # Framework: posting the events about the handlers progress/errors.
#   - apiGroups: [""]
#     resources: [events]
#     verbs: [create]
#   - apiGroups: ["workload.nephio.org"]
#     resources: [ausfdeployments,ausfdeployments/status]
#     verbs: [list, watch, update, patch]
#   - apiGroups: [""]
#     resources: [pods, serviceaccounts, configmaps, services, persistentvolumeclaims]
#     verbs:  [get, list, watch, create, update, patch, delete]
#   - apiGroups: ["apps","extensions"]
#     resources: [deployments,deployments/status]
#     verbs:  [get, list, watch, create, update, patch, delete]
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   namespace: oaiops
#   name: oai-ausf-operator-rolebinding-namespaced
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: Role
#   name: oai-ausf-operator-role
# subjects:
#   - kind: ServiceAccount
#     name: oai-ausf-operator
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oai-ausf-op-conf
  namespace: oaiops  
data:
  ausf.yaml: |
    image: 'docker.io/oaisoftwarealliance/oai-ausf:v1.5.1'
    ports: 
      - name: 'http'
        port: 80
        protocol: TCP
    fqdn:
      nrf: 'nrf-regional'
      udm: 'udm-regional'
    compute:
      req:
        cpu: '100m'
        memory: '256Mi'
      limits:
        cpu: '100m'
        memory: '256Mi'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oai-ausf-nf-conf
  namespace: oaiops
data:
  ausf.conf: |
    AUSF =
    {
      INSTANCE_ID = 0;
      PID_DIRECTORY = "/var/run";
      AUSF_NAME = "oai-ausf";
      LOG_LEVEL = "{{ conf["logLevel"] if "logLevel" in conf.keys() else 'debug' }}";

      INTERFACES:{
        # AUSF binded interface for SBI interface (e.g., communication with AMF, UDM)
        SBI:{
            INTERFACE_NAME = "{{ conf['nfInterfaces']['sbi'] if 'nfInterfaces' in conf.keys() and 'sbi' in conf['nfInterfaces'].keys() else 'eth0' }}";
            IPV4_ADDRESS   = "read";
            # YOUR NETWORK CONFIG HERE (default: 80)
            PORT           = 80;
            # YOUR API VERSION FOR UDM CONFIG HERE (default: v1)
            API_VERSION    = "v1";
            # YOUR NETWORK CONFIG HERE (default: 8080)
            HTTP2_PORT     = 8080;
        };
      };

      # SUPPORT FEATURES
      SUPPORT_FEATURES:{
        # STRING, {"yes", "no"},
        # Set to yes if AUSF will relying on a DNS to resolve UDM's FQDN
        USE_FQDN_DNS = "yes";
        # Set to yes to enable HTTP2 for AMF server
        USE_HTTP2    = "no";
        # Set to 'yes' if AUSF resgisters to an NRF
        REGISTER_NRF = "no";
      }

      # UDM Information
      UDM:{
        IPV4_ADDRESS   = "127.0.0.1";
        # YOUR NETWORK CONFIG HERE  (default: 80)
        PORT           = 80;
        # YOUR API VERSION FOR UDM CONFIG HERE
        API_VERSION    = "v1";
        # YOUR UDM FQDN CONFIG HERE
        FQDN           = "{{ conf['fqdn']['udm'] if 'fqdn' in conf.keys() and 'udm' in conf['fqdn'].keys() else 'oai-udm' }}"
      };

      NRF :
      {
        IPV4_ADDRESS   = "127.0.0.1";
        # YOUR NRF CONFIG HERE (default: 80)
        PORT           = 80;
        # YOUR NRF API VERSION HERE
        API_VERSION    = "v1";
        FQDN           = "{{ conf['fqdn']['nrf'] if 'fqdn' in conf.keys() and 'nrf' in conf['fqdn'].keys() else 'oai-nrf' }}";
      };
    };

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-ausf-controller
  namespace: oaiops
  labels:
    app.kubernetes.io/name: oai-ausf
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: oai-ausf
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oai-ausf
    spec:
      # securityContext:
      #   runAsGroup: 0
      #   runAsUser: 0
      imagePullSecrets:
      - name: regcred
      containers:
      - name: ausf-controller
        image: "docker.io/arorasagar/oai-ausf-controller:v1.5.1"
        imagePullPolicy: Always
        command:
        - 'kopf'
        - 'run' 
        - '/root/.local/controller.py'
        - '--all-namespaces'
        - '--liveness=http://0.0.0.0:8080/healthz'
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        env:
          - name: 'NF_TYPE'
            value: 'ausf'
          - name: 'DEPLOYMENT_FETCH_INTERVAL'
            value: '1'
          - name: 'DEPLOYMENT_FETCH_ITERATIONS'
            value: '100'
          - name: 'NF_CONF_PATH'
            value: '/tmp/nf/ausf.conf'
          - name: 'OP_CONF_PATH'
            value: '/tmp/op/ausf.yaml'
        volumeMounts:
          - mountPath: /tmp/op
            name: opconf
          - mountPath: /tmp/nf
            name: nfconf
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "250Mi"
            cpu: "300m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
      volumes:
      - configMap:
          name: oai-ausf-op-conf
        name: opconf
      - configMap:
          name: oai-ausf-nf-conf
        name: nfconf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccountName: oai-ausf-operator
      terminationGracePeriodSeconds: 5
