################################################################################
# Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The OpenAirInterface Software Alliance licenses this file to You under
# the terms found in the LICENSE file in the root of this source tree.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the OpenAirInterface (OAI) Software Alliance:
#      contact@openairinterface.org
##################################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: oaiops
  name: oai-smf-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oai-smf-operator-cluster-role
rules:
  - apiGroups: [""]
    resources: [events]
    verbs: [create]
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [get, list, watch, create, update, patch]
  # - apiGroups: ["workload.nephio.org"]
  #   resources: [smfdeployments]
  #   verbs: [list, watch]
  - apiGroups: ["ref.nephio.org"]
    resources: [configs,config]
    verbs: [list, watch, update, patch, get]
  - apiGroups: ["workload.nephio.org"]
    resources: [smfdeployments,smfdeployments/status]
    verbs: [list, watch, update, patch]
  - apiGroups: [""]
    resources: [pods, serviceaccounts, configmaps, services, persistentvolumeclaims]
    verbs:  [get, list, watch, create, update, patch, delete]
  - apiGroups: ["apps","extensions"]
    resources: [deployments,deployments/status]
    verbs:  [get, list, watch, create, update, patch, delete]
  - apiGroups: ["k8s.cni.cncf.io"]
    resources: [network-attachment-definitions]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]
  - apiGroups: [admissionregistration.k8s.io/v1, admissionregistration.k8s.io/v1beta1]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oai-smf-operator-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oai-smf-operator-cluster-role
subjects:
  - kind: ServiceAccount
    name: oai-smf-operator
    namespace: oaiops
## In case you want to restrict to a namespace uncomment this role and remove the rights from cluster role
#---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   namespace: oaiops
#   name: oai-smf-operator-role
# rules:
#   # Framework: posting the events about the handlers progress/errors.
#   - apiGroups: [""]
#     resources: [events]
#     verbs: [create]
#   - apiGroups: ["workload.nephio.org"]
#     resources: [smfdeployments,smfdeployments/status]
#     verbs: [list, watch, update, patch]
#   - apiGroups: [""]
#     resources: [pods, serviceaccounts, configmaps, services, persistentvolumeclaims]
#     verbs:  [get, list, watch, create, update, patch, delete]
#   - apiGroups: ["apps","extensions"]
#     resources: [deployments,deployments/status]
#     verbs:  [get, list, watch, create, update, patch, delete]
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   namespace: oaiops
#   name: oai-smf-operator-rolebinding-namespaced
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: Role
#   name: oai-smf-operator-role
# subjects:
#   - kind: ServiceAccount
#     name: oai-smf-operator
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oai-smf-op-conf
  namespace: oaiops
data:
  smf.yaml: |
    nad: 
      parent: 'eth0'
      create: False
    ports:
      - name: 'n4'
        port: 8805
        protocol: UDP
      - name: 'sbi'
        port: 80
        protocol: TCP
    nfInterfaces:
      n4: 'n4'
      sbi: 'eth0'
    compute:
      req:
        cpu: '100m'
        memory: '512Mi'
      limits:
        cpu: '100m'
        memory: '512Mi'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oai-smf-nf-conf
  namespace: oaiops
data:
  smf.yaml: |
    # Log level for all the NFs
    log_level:
      general: {{ conf['logLevel'] }}
    # If you enable registration, the other NFs will use the NRF discovery mechanism
    register_nf:
      general: yes
    http_version: 2
    ## general single_nssai configuration
    ## Defines YAML anchors, which are reused in the config file
    snssais:
      {%- for i in conf['nssai'] %}
      - &slice_{{ conf['nssai'].index(i) }}
        sst: {{ i['sst'] }}
        sd: {{ i['sd'] if 'sd' in i.keys() else 'FFFFFF' }}
      {%- endfor %}
    ############## SBI Interfaces
    ### Each NF takes its local SBI interfaces and remote interfaces from here, unless it gets them using NRF discovery mechanisms
    nfs:
      amf:
        host: {{ conf['fqdn']['amf'] }}
        sbi:
          port: 80
          api_version: v1
      smf:
        host: {{ conf['fqdn']['smf'] }}
        sbi:
          port: 80
          api_version: v1
          interface_name: {{ conf['nfInterfaces']['sbi'] }}
        n4:
          interface_name: {{ conf['nfInterfaces']['n4'] }}
          port: 8805
      udm:
        host: {{ conf['fqdn']['udm'] }}
        sbi:
          port: 80
          api_version: v1
      nrf:
        host: {{ conf['fqdn']['nrf'] }}
        sbi:
          port: 80
          api_version: v1
    ############## NF-specific configuration
    smf:
      ue_mtu: {{ conf['ueSettings']['mtu'] }}
      support_features:
        use_local_subscription_info: yes # Use infos from local_subscription_info or from UDM
        use_local_pcc_rules: yes # Use infos from local_pcc_rules or from PCF
        discover_upf: yes
      # we resolve from NRF, this is just to configure usage_reporting
      upfs:
        {%- for i in conf['upfs'] %}
        - host: {{ i }}
          config:
            enable_usage_reporting: no
        {%- endfor %}
      ue_dns:
        primary_ipv4: {{ conf['ueSettings']['primary'] }}
        primary_ipv6: "2001:4860:4860::8888"
        secondary_ipv4: {{ conf['ueSettings']['secondary'] }}
        secondary_ipv6: "2001:4860:4860::8888"
      ims:
        pcscf_ipv4: "192.168.70.139"
        pcscf_ipv6: "fe80::7915:f408:1787:db8b"
      # the DNN you configure here should be configured in "dnns"
      # follows the SmfInfo datatype from 3GPP TS 29.510
      smf_info:
        sNssaiSmfInfoList:
          {%- for i in conf['nssai'] %}
          - sNssai: *slice_{{ conf['nssai'].index(i) }}
            dnnSmfInfoList:
          {%- for d in i['dnnList'] %}
              - dnn: {{ d }}
          {%- endfor %}
          {%- endfor %}
      local_subscription_infos:
        {%- for i in conf['nssai'] %}
        {%- for d in i['dnnList'] %}
        - single_nssai: *slice_{{ conf['nssai'].index(i) }}
          dnn: {{ d }}
          qos_profile:
            5qi: 5
            session_ambr_ul: "200Mbps"
            session_ambr_dl: "400Mbps"
        {%- endfor %}
        {%- endfor %}
    ## DNN configuration
    dnns:
      {%- for l in conf['dnns'] %}
      - dnn: "{{ l['dnn'] }}"
        pdu_session_type: "IPV4"
        ipv4_subnet: "{{ l['subnet'] }}"
      {%- endfor %}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-smf-controller
  namespace: oaiops
  labels:
    app.kubernetes.io/name: oai-smf
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: oai-smf
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oai-smf
    spec:
      securityContext:
        runAsGroup: 0
        runAsUser: 0
      # imagePullSecrets:
      # - name: regcred
      containers:
      - name: smf-controller
        image: "hydrogen.local/oai-smf-controller:develop"
        imagePullPolicy: IfNotPresent
        env:
          - name: 'NF_TYPE'
            value: 'smf'
          - name: 'DEPLOYMENT_FETCH_INTERVAL'
            value: '1'
          - name: 'DEPLOYMENT_FETCH_ITERATIONS'
            value: '100'
          - name: 'NF_CONF_PATH'
            value: '/tmp/nf/smf.yaml'
          - name: 'OP_CONF_PATH'
            value: '/tmp/op/smf.yaml'
          - name: 'TESTING'
            value: 'no'
          - name: 'KUBERNETES_BASE_URL'
            value: 'https://kubernetes.default.svc'
        volumeMounts:
          - mountPath: /tmp/op
            name: opconf
          - mountPath: /tmp/nf
            name: nfconf
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "50m"
        # livenessProbe:
        #   httpGet:
        #     path: /healthz
        #     port: 8080
        #   initialDelaySeconds: 2
        #   periodSeconds: 5
      volumes:
      - configMap:
          name: oai-smf-op-conf
        name: opconf
      - configMap:
          name: oai-smf-nf-conf
        name: nfconf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccountName: oai-smf-operator
      terminationGracePeriodSeconds: 5