apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "oai-gnb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: n3
      port: 2152
      targetPort: 2152
      protocol: 
    - name: n2
      port: 36412
      targetPort: 36412
      protocol: SCTP
  selector:
    {{- include "oai-gnb.selectorLabels" . | nindent 4 }}
