apiVersion: ref.nephio.org/v1alpha1
kind: Config
metadata:
  name: amf-config
spec:
  config:
    apiVersion: workload.nephio.org/v1alpha1
    kind: AMFDeployment
    metadata:
      name: amf-config
      namespace: default
    spec:
      logLevel: info
      plmn:
        mcc: '001'
        mnc: '01'
        tac: '0x0001'
      nssai:
        - sst: 1
          sd: 'FFFFFF'
        - sst: 1
          sd: '000001'
      image: 'docker.io/oaisoftwarealliance/oai-amf:develop'
      fqdn:
        smf: 'oai-smf'
        ausf: 'oai-ausf'
        nrf: 'oai-nrf'
        udm: 'oai-udm'
---
apiVersion: workload.nephio.org/v1alpha1
kind: AMFDeployment
metadata:
  name: oai-amf
spec:
  capacity:
    maxSubscribers: 100
  interfaces:
  - name: n2
    ipv4:
      address: 14.0.0.2/24
      gateway: 13.0.0.1
  networkInstances:
  - name: vpc-ran
    interfaces:
    - n2
  configRefs:
  - name: amf-config
    namespace: default
    apiVersion: ref.nephio.org/v1alpha1
    kind: Config