apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: oai-amf-n2
spec:
  config: '{"cniVersion":"0.3.1","plugins":[{"type":"macvlan","capabilities":{"ips":true},"master":"eth0","mode":"bridge","ipam":{"type":"static","addresses":[{"address":"172.2.2.254/24","gateway":"172.2.2.1"}]}},{"type":"tuning","capabilities":{"mac":true},"ipam":{}}]}'
---
apiVersion: ref.nephio.org/v1alpha1
kind: Config
metadata:
  name: common-core-ran-config
spec:
  config:
    apiVersion: nfconfig.nephio.org/v1alpha1
    kind: CommonCoreRANConfig
    metadata:
      name: common-core-ran
      namespace: default
    spec:
      plmnInfo:
        - mcc: "001"
          mnc: "01"
          tac: 1
          nssai:
            - sst: 1
              sd: ffffff
              dnnInfo:
                - name: internet
                  sessionType: ipv4
                  dns: 8.8.8.8
            - sst: 2
              sd: ffffff
              dnnInfo:
                - name: internet
                  sessionType: ipv4
                  dns: 8.8.8.8
      communicationModel: 
        - name: woNrf
          nrfUri: http://nrf-nnrf:8000
---
apiVersion: ref.nephio.org/v1alpha1
kind: Config
metadata:
  name: amf-config
spec:
  config:
    apiVersion: nfconfig.nephio.org/v1alpha1
    kind: AmfConfig
    metadata:
      name: amf
      namespace: default
    spec:
      amfName: amf
      servedGuami:
        - plmnId:
            mcc: "001"
            mnc: "01"
          amfId:
            amfRegionId: "01"
            amfSetId: "001"
            amfPointer: "01"
---
apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata:
  name: oai-amf
spec:
  provider: amf.openairinterface.org
  capacity:
    maxSubscribers: 100
  interfaces:
  - name: n2
    ipv4:
      address: 14.0.0.2/24
      gateway: 13.0.0.1
  networkInstances:
  - name: vpc-ran
    interfaces:
    - n2
  parametersRefs:
  - name: common-core-ran-config
    apiVersion: ref.nephio.org/v1alpha1
    kind: Config
  - name: amf-config
    apiVersion: ref.nephio.org/v1alpha1
    kind: Config