################################################################################
# Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The OpenAirInterface Software Alliance licenses this file to You under
# the terms found in the LICENSE file in the root of this source tree.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the OpenAirInterface (OAI) Software Alliance:
#      contact@openairinterface.org
##################################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: oai-ausf-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oai-ausf-operator-cluster-role
rules:
  - apiGroups: [""]
    resources: [events]
    verbs: [create]
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    resourceNames: ["anyuid"]
    verbs: [use]
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [get, list, watch, create, update, patch]
  - apiGroups: ["ref.nephio.org"]
    resources: [configs,config]
    verbs: [list, watch, update, patch, get]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: [roles,rolebindings]
    verbs: [get, create, delete, patch]
  - apiGroups: ["workload.nephio.org"]
    resources: [nfdeployments,nfdeployments/status,nfconfigs,nfdeployments/finalizers]
    verbs: [get, list, watch, update, patch]
  - apiGroups: [""]
    resources: [pods, serviceaccounts, configmaps, services, persistentvolumeclaims,services/finalizers,serviceaccounts/finalizers]
    verbs:  [get, list, watch, create, update, patch, delete]
  - apiGroups: ["apps","extensions"]
    resources: [deployments,deployments/status,deployments/finalizers]
    verbs:  [get, list, watch, create, update, patch, delete]
  - apiGroups: ["k8s.cni.cncf.io"]
    resources: [network-attachment-definitions]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]
  - apiGroups: [admissionregistration.k8s.io/v1, admissionregistration.k8s.io/v1beta1]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oai-ausf-operator-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oai-ausf-operator-cluster-role
subjects:
  - kind: ServiceAccount
    name: oai-ausf-operator
    namespace: default
## In case you want to restrict to a namespace uncomment this role and remove the rights from cluster role
#---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   namespace: default
#   name: oai-ausf-operator-role
# rules:
#   # Framework: posting the events about the handlers progress/errors.
#   - apiGroups: [""]
#     resources: [events]
#     verbs: [create]
#   - apiGroups: ["workload.nephio.org"]
#     resources: [ausfdeployments,ausfdeployments/status]
#     verbs: [list, watch, update, patch]
#   - apiGroups: [""]
#     resources: [pods, serviceaccounts, configmaps, services, persistentvolumeclaims]
#     verbs:  [get, list, watch, create, update, patch, delete]
#   - apiGroups: ["apps","extensions"]
#     resources: [deployments,deployments/status]
#     verbs:  [get, list, watch, create, update, patch, delete]
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   namespace: default
#   name: oai-ausf-operator-rolebinding-namespaced
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: Role
#   name: oai-ausf-operator-role
# subjects:
#   - kind: ServiceAccount
#     name: oai-ausf-operator
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oai-ausf-op-conf
data:
  ausf.yaml: |
    nfInterfaces:
      sbi: 'eth0'
    ports: 
      - name: 'http'
        port: 80
        protocol: TCP
    compute:
      req:
        cpu: '100m'
        memory: '256Mi'
      limits:
        cpu: '100m'
        memory: '256Mi'
    logLevel: info
    image: 'docker.io/oaisoftwarealliance/oai-ausf:v2.0.0'
    fqdn:
      udm: localhost
      nrf: localhost
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oai-ausf-nf-conf
data:
  ausf.yaml: |
    ############# Common configuration
    # Log level
    log_level:
      ausf: {{ conf['logLevel'] }}
    # If you enable registration, the NF will use the NRF discovery mechanism
    register_nf:
      ausf: 'yes'
    http_version: 2  # allowed value 1 and 2, make sure all NFs use the same HTTP version
    ############## SBI Interfaces
    ### Each NF takes its local SBI interfaces and remote interfaces from here, unless it gets them using NRF discovery mechanisms
    nfs:
      ausf:
        host: {{ conf['fqdn']['ausf'] }}
        sbi:
          port: 80
          api_version: v1
          interface_name: {{ conf['nfInterfaces']['sbi'] }}
      udm:
        host: {{ conf['fqdn']['udm'] }}
        sbi:
          port: 80
          api_version: v1
      nrf:
        host: {{ conf['fqdn']['nrf'] }}
        sbi:
          port: 80
          api_version: v1
    ############## NF-specific configuration
    ausf:
      ausf_name: "OAI-AUSF"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-ausf-controller
  labels:
    app.kubernetes.io/name: oai-ausf
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: oai-ausf
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oai-ausf
    spec:
      securityContext:
        runAsGroup: 0
        runAsUser: 0
      imagePullSecrets:
      - name: regcred
      containers:
      - name: ausf-controller
        image: "oai-ausf-controller:v2.0.0"
        imagePullPolicy: IfNotPresent
        env:
          - name: 'NF_TYPE'
            value: 'ausf'
          - name: 'DEPLOYMENT_FETCH_INTERVAL'
            value: '1'
          - name: 'DEPLOYMENT_FETCH_ITERATIONS'
            value: '100'
          - name: 'NF_CONF_PATH'
            value: '/tmp/nf/ausf.yaml'
          - name: 'OP_CONF_PATH'
            value: '/tmp/op/ausf.yaml'
          - name: 'TESTING'
            value: 'yes'
          - name: 'KUBERNETES_BASE_URL'
            value: 'http://kubernetes.default.svc'
        volumeMounts:
          - mountPath: /tmp/op
            name: opconf
          - mountPath: /tmp/nf
            name: nfconf
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "50m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5
      volumes:
      - configMap:
          name: oai-ausf-op-conf
        name: opconf
      - configMap:
          name: oai-ausf-nf-conf
        name: nfconf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccountName: oai-ausf-operator
      terminationGracePeriodSeconds: 5
