apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: oai-smf-n4
spec:
  config: '{"cniVersion":"0.3.1","plugins":[{"type":"macvlan","capabilities":{"ips":true},"master":"eth0","mode":"bridge","ipam":{"type":"static","addresses":[{"address":"172.1.1.254/24","gateway":"172.1.1.1"}]}},{"type":"tuning","capabilities":{"mac":true},"ipam":{}}]}'
---
apiVersion: ref.nephio.org/v1alpha1
kind: Config
metadata:
  name: smf-regional-upf-edge01
spec:
  config:
    provider: upf.openairinterface.org
    apiVersion: workload.nephio.org/v1alpha1
    kind: NFDeployment
    metadata:
      name: upf-edge01
      namespace: default
    spec:
      capacity:
        maxDownlinkThroughput: 5G
        maxUplinkThroughput: 5G
      interfaces:
      - name: n3
        ipv4:
          address: 172.3.0.254/24
          gateway: 172.3.0.1
        vlanID: 4
      - name: n4
        ipv4:
          address: 172.1.1.253/24
          gateway: 172.1.1.1
        vlanID: 2
      - name: n6
        ipv4:
          address: 172.0.1.254/24
          gateway: 172.0.1.1
        vlanID: 3
      networkInstances:
      - name: vpc-internal
        interfaces:
        - n4
      - name: vpc-internet
        dataNetworks:
        - name: internet
          pool:
          - prefix: 10.3.0.0/24
        interfaces:
        - n6
      - name: vpc-ran
        interfaces:
        - n3
---
apiVersion: ref.nephio.org/v1alpha1
kind: Config
metadata:
  name: smf-regional-upf-edge02
spec:
  config:
    provider: upf.openairinterface.org
    apiVersion: workload.nephio.org/v1alpha1
    kind: NFDeployment
    metadata:
      name: upf-edge02
      namespace: default
    spec:
      capacity:
        maxDownlinkThroughput: 5G
        maxUplinkThroughput: 5G
      interfaces:
      - name: n3
        ipv4:
          address: 172.3.1.253/24
          gateway: 172.3.1.1
        vlanID: 4
      - name: n4
        ipv4:
          address: 172.1.1.252/24
          gateway: 172.1.1.1
        vlanID: 2
      - name: n6
        ipv4:
          address: 172.0.1.253/24
          gateway: 172.0.1.1
        vlanID: 3
      networkInstances:
      - name: vpc-internal
        interfaces:
        - n4
      - name: vpc-internet
        dataNetworks:
        - name: internet
          pool:
          - prefix: 10.3.0.0/24
        interfaces:
        - n6
      - name: vpc-ran
        interfaces:
        - n3
---
apiVersion: workload.nephio.org/v1alpha1
kind: NFConfig
metadata:
  name: oai-smf-config
spec:
  configRefs:
    - apiVersion: cellular.nephio.org/v1alpha1
      kind: PLMN
      metadata:
        name: oai-plmn
      spec:
        plmnInfo:
          - plmnID:
              mcc: "001"
              mcc: "01"
            tac: 1
            nssai:
              - sst: 1
                sd: ffffff
                dnnInfo:
                  - name: internet
                    sessionType: ipv4
                    dns: 8.8.8.8
---
apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata:
  name: oai-smf
spec:
  provider: smf.openairinterface.org
  capacity:
    maxNFConnections: 10
    maxSessions: 500
  interfaces:
  - name: n4
    ipv4:
      address: 172.1.1.254/24
      gateway: 172.1.1.1
    vlanID: 2
  networkInstances:
  - name: vpc-internal
    interfaces:
    - n4
  parametersRefs:
  - name: oai-smf-config
    apiVersion: workload.nephio.org/v1alpha1
    kind: NFConfig
  - name: smf-regional-upf-edge01
    apiVersion: ref.nephio.org/v1alpha1
    kind: Config
  - name: smf-regional-upf-edge02
    apiVersion: ref.nephio.org/v1alpha1
    kind: Config