apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: cucp-regional-n2
  namespace: oaicp
spec:
  config: '{"cniVersion":"0.3.1","name": "cucp-regional-n2","plugins":[{"type":"macvlan","capabilities":{"ips":true},"master":"eth0","mode":"bridge","ipam":{"type":"static"}}]}'
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: cucp-regional-f1c
  namespace: oaicp
spec:
  config: '{"cniVersion":"0.3.1","name": "cucp-regional-f1c","plugins":[{"type":"macvlan","capabilities":{"ips":true},"master":"eth0","mode":"bridge","ipam":{"type":"static"}}]}'
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: cucp-regional-e1
  namespace: oaicp
spec:
  config: '{"cniVersion":"0.3.1","name": "cucp-regional-e1","plugins":[{"type":"macvlan","capabilities":{"ips":true},"master":"eth0","mode":"bridge","ipam":{"type":"static"}}]}'
---
apiVersion: workload.nephio.org/v1alpha1
kind: NFConfig
metadata:
  name: cucp-regional-config
  namespace: oaicp
spec:
  configRefs:
    - apiVersion: workload.nephio.org/v1alpha1
      kind: RANConfig
      metadata:
        name: ranconfig
      spec:
        nrCellId: 1
        gNBID: 12
        gNBName: oai-benetel
    - apiVersion: workload.nephio.org/v1alpha1
      kind: PLMN
      metadata:
        name: plmn
      spec:
        PLMNInfo:
        - plmnID:
            mcc: "001"
            mnc: "01"
          tac: 1
          nssai:
          - sd: ffffff
            sst: 1
---
apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata:
  name: cucp-regional
  namespace: oaicp
spec:
  provider: cucp.openairinterface.org
  interfaces:
  - name: n2
    ipv4:
      address: 192.168.30.4/24
      gateway: 192.168.30.1
    vlanID: 30
  - name: f1c
    ipv4:
      address: 192.168.32.2/24
      gateway: 192.168.32.1
    vlanID: 32
  - name: e1
    ipv4:
      address: 192.168.33.2/24
      gateway: 192.168.33.1
    vlanID: 33
  networkInstances:
  - name: vpc-ran
    interfaces:
    - n2
  - name: vpc-cudu-f1
    interfaces:
    - f1c
  - name: vpc-cu-e1
    interfaces:
    - e1
  parametersRefs:
  - name: cucp-regional-config
    apiVersion: workload.nephio.org/v1alpha1
    kind: NFConfig
    