apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: oai-upf-0
spec:
  config: '{
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "macvlan",
          "capabilities": { "ips": true },
          "master": "eth0",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "routes": []
          }
        }, {
          "capabilities": { "mac": true },
          "type": "tuning"
        }
      ]
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: oai-upf-1
spec:
  config: '{
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "macvlan",
          "capabilities": { "ips": true },
          "master": "eth0",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "routes": []
          }
        }, {
          "capabilities": { "mac": true },
          "type": "tuning"
        }
      ]
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: oai-upf-2
spec:
  config: '{
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "macvlan",
          "capabilities": { "ips": true },
          "master": "eth0",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "routes": []
          }
        }, {
          "capabilities": { "mac": true },
          "type": "tuning"
        }
      ]
    }'
---
apiVersion: v1
kind: Pod
metadata:
  name: testpod
  labels:
    app: testmultus
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
        {"name": "oai-upf-0",
         "interface": "n3",
         "ips": ["10.10.5.3/24"],
         "gateway": ["10.10.5.1"]
        },
        {"name": "oai-upf-1",
         "interface": "n4",
         "ips": ["192.168.100.3/24"],
         "gateway": ["192.168.100.1"]
        },
        {"name": "oai-upf-2",
         "interface": "n6",
         "ips": ["10.20.3.3/24"],
         "gateway": ["10.20.3.1"]
        }
            ]'
spec:
  containers:
  - name: testpod
    command: ["/bin/sh", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine
